INSERT INTO pergunta (PERGUNTA, NIVEL_PERGUNTA) VALUES ('Qual tipo de rede é uma rede local?', 1);
INSERT INTO pergunta (PERGUNTA, NIVEL_PERGUNTA) VALUES ('Protocolo TCP pertence a qual camada?', 1);
INSERT INTO pergunta (PERGUNTA, NIVEL_PERGUNTA) VALUES ('Em que ano foi criada a "Arpanet"?', 1);

INSERT INTO pergunta (PERGUNTA, NIVEL_PERGUNTA) VALUES ('Quantas camadas tem o modelo OSI?', 2);
INSERT INTO pergunta (PERGUNTA, NIVEL_PERGUNTA) VALUES ('Em que ano foi criado o modelo OSI?', 2);

INSERT INTO pergunta (PERGUNTA, NIVEL_PERGUNTA) VALUES ('Qual desses protoclos NÃO é um protocolo da camada de Rede', 3);
INSERT INTO pergunta (PERGUNTA, NIVEL_PERGUNTA) VALUES ('Qual é a função DNS?', 3);

INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('LAN', 1, 1);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('MAN', 1, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('WAN', 1, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('PAN', 1, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('YAN', 1, 0);

INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('Física', 2, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('Enlace', 2, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('Rede', 2, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('Transporte', 2, 1);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('Sessão', 2, 0);

INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1968', 3, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1969', 3, 1);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1970', 3, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1971', 3, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1972', 3, 0);

INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('4', 4, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('5', 4, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('6', 4, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('7', 4, 1);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('8', 4, 0);

INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1980', 5, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1981', 5, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1982', 5, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1983', 5, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1984', 5, 1);

INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1980', 6, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1981', 6, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1982', 6, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1983', 6, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1984', 6, 1);

INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('Fornecer IP do usuário', 7, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('Máscara de sub-rede', 7, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('Converter endereços IP em nomes', 7, 1);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('IP do default gateway', 7, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('Protocolo para transferencia de pacotes', 7, 1);



