INSERT INTO pergunta (PERGUNTA, NIVEL_PERGUNTA) VALUES ('Data nasc pele', 1);

INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1910', 1, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1920', 1, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1930', 1, 0);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1940', 1, 1);
INSERT INTO RESPOSTA (RESPOSTA, ID_PERGUNTA, IS_CORRETA) VALUES ('1950', 1, 0);

